apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../applications/monitoring/namespace.yaml
- ../../../applications/monitoring/grafana
- ../../../applications/monitoring/prometheus