apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../applications/logging/namespace.yaml
- ../../../applications/logging/helmrepository.yaml
- ../../../applications/logging/logstash
- ../../../applications/logging/kibana
- ../../../applications/logging/elasticsearch