apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../applications/infrastructure/namespace.yaml
- ../../../applications/infrastructure/metallb
- ../../../applications/infrastructure/cert-manager
- ../../../applications/infrastructure/nginx-ingress